### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by just-injoey**
I have updated the readme.md file. 
I have added the steps to Setup the project and given a brief description about the project.

### CODE REVIEW

**Comment by NiteeshK21** [comment]
Hey!
All you've done is good but the icons of open-source and etc. which you've added, align them to center.

**Comment by just-injoey** [comment]
> Hey! All you've done is good but the icons of open-source and etc. which you've added, align them to center.

Ok, I will update the README.md file

**Comment by just-injoey** [comment]
> Hey! All you've done is good but the icons of open-source and etc. which you've added, align them to center.

Actually in my system the mentioned icons are centrally aligned.
image

My System Specs:
OS : Windows 10
Browser: Google Chrome

**Comment by NiteeshK21** [comment]
Great Work!
I've merged your pull request.

**Pull request merged**
